<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="images.aspx.cs" Inherits="PhotoAlbum.images" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    </head>
<body style="height: 246px">
    <form id="form1" runat="server">
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
&nbsp;select image:
        <asp:FileUpload ID="FileUpload1" runat="server" />
        <br />
        <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
        <asp:Button ID="btnUpload" runat="server" OnClick="btnUpload_Click" Text="upload" />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:BoundField HeaderText ="ImageName" DataField="imageName" />
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:HyperLink ID="MyLink" Target="_blank" NavigateUrl='<%# Eval("imageID","~/imageHandler.ashx? imageID={0}") %>' runat="server"> Display</asp:HyperLink>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ImageGalleryConnectionString1 %>" DeleteCommand="DELETE FROM [Images] WHERE [imageID] = @imageID" InsertCommand="INSERT INTO [Images] ([imageName], [image]) VALUES (@imageName, @image)" SelectCommand="SELECT * FROM [Images]" UpdateCommand="UPDATE [Images] SET [imageName] = @imageName, [image] = @image WHERE [imageID] = @imageID">
            <DeleteParameters>
                <asp:Parameter Name="imageID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="imageName" Type="String" />
                <asp:Parameter Name="image" Type="Object" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="imageName" Type="String" />
                <asp:Parameter Name="image" Type="Object" />
                <asp:Parameter Name="imageID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
